<?php
$names = array (
  'article' => '文章',
  'brand' => '品牌',
  'buy' => '求购',
  'charge' => '充值',
  'company' => '公司',
  'contact' => '联系内容',
  'content' => '信息内容',
  'exhibit' => '展会',
  'footer' => 'WAP页脚',
  'header' => 'WAP页头',
  'index' => 'WAP首页',
  'info' => '信息',
  'job' => '招聘',
  'know' => '知道',
  'login' => '登录',
  'message' => '站内信',
  'message_send' => '发送站内信',
  'msg' => '信息提示',
  'product' => '产品',
  'quote' => '报价',
  'resume' => '简历',
  'sell' => '供应',
);
?>