<?php
  class Keke_witkey_message_config_class{
        var $_db;
        var $_tablename;
	    var $_dbop;
	    	 var $_msg_cofig_id; //主键 		 var $_reg_isnotice; 		 var $_task_pub_isnotice; 		 var $_tender_isnotice; 		 var $_task_auth_fail_isnotice; 		 var $_task_auth_success_isnotice; 		 var $_pay_fail_isnotice; 		 var $_user_auth_success_isnotice; 		 var $_user_auth_fail_isnotice; 		 var $_pay_success_isnotice; 		 var $_draw_success_isnotice; 		 var $_freeze_isnotice; 		 var $_task_freeze_isnotice; 		 var $_update_password_isnotice; 		 var $_msg_send_type; 		 var $_on_time; 
	    var $_replace=0; //insert into or replace into ?
	    var $_where;     //查，改，删条件
	     function  keke_witkey_message_config_class(){ //构造方法			 $this->_db = new db_factory ( );			 $this->_dbop = $this->_db->create(DBTYPE);			 $this->_tablename = TABLEPRE."witkey_message_config";		 }	    
	    		function getMsg_cofig_id(){			 return $this->_msg_cofig_id ;		}		function getReg_isnotice(){			 return $this->_reg_isnotice ;		}		function getTask_pub_isnotice(){			 return $this->_task_pub_isnotice ;		}		function getTender_isnotice(){			 return $this->_tender_isnotice ;		}		function getTask_auth_fail_isnotice(){			 return $this->_task_auth_fail_isnotice ;		}		function getTask_auth_success_isnotice(){			 return $this->_task_auth_success_isnotice ;		}		function getPay_fail_isnotice(){			 return $this->_pay_fail_isnotice ;		}		function getUser_auth_success_isnotice(){			 return $this->_user_auth_success_isnotice ;		}		function getUser_auth_fail_isnotice(){			 return $this->_user_auth_fail_isnotice ;		}		function getPay_success_isnotice(){			 return $this->_pay_success_isnotice ;		}		function getDraw_success_isnotice(){			 return $this->_draw_success_isnotice ;		}		function getFreeze_isnotice(){			 return $this->_freeze_isnotice ;		}		function getTask_freeze_isnotice(){			 return $this->_task_freeze_isnotice ;		}		function getUpdate_password_isnotice(){			 return $this->_update_password_isnotice ;		}		function getMsg_send_type(){			 return $this->_msg_send_type ;		}		function getOn_time(){			 return $this->_on_time ;		}		function getWhere(){			 return $this->_where ;		}
	    		function setMsg_cofig_id($value){ 			 $this->_msg_cofig_id = $value;		}		function setReg_isnotice($value){ 			 $this->_reg_isnotice = $value;		}		function setTask_pub_isnotice($value){ 			 $this->_task_pub_isnotice = $value;		}		function setTender_isnotice($value){ 			 $this->_tender_isnotice = $value;		}		function setTask_auth_fail_isnotice($value){ 			 $this->_task_auth_fail_isnotice = $value;		}		function setTask_auth_success_isnotice($value){ 			 $this->_task_auth_success_isnotice = $value;		}		function setPay_fail_isnotice($value){ 			 $this->_pay_fail_isnotice = $value;		}		function setUser_auth_success_isnotice($value){ 			 $this->_user_auth_success_isnotice = $value;		}		function setUser_auth_fail_isnotice($value){ 			 $this->_user_auth_fail_isnotice = $value;		}		function setPay_success_isnotice($value){ 			 $this->_pay_success_isnotice = $value;		}		function setDraw_success_isnotice($value){ 			 $this->_draw_success_isnotice = $value;		}		function setFreeze_isnotice($value){ 			 $this->_freeze_isnotice = $value;		}		function setTask_freeze_isnotice($value){ 			 $this->_task_freeze_isnotice = $value;		}		function setUpdate_password_isnotice($value){ 			 $this->_update_password_isnotice = $value;		}		function setMsg_send_type($value){ 			 $this->_msg_send_type = $value;		}		function setOn_time($value){ 			 $this->_on_time = $value;		}		function setWhere($value){ 			 $this->_where = $value;		}
	    
    	   public  function __set($property_name, $value) {
		 		$this->$property_name = $value; 
			}
			public function __get($property_name) { 
				if (isset ( $this->$property_name )) { 
					return $this->$property_name; 
				} else { 
					return null; 
				} 
			}
    	
	    /**		 * 表keke_witkey_message_config创建或新增一条记录		 * @return 返回新增ID		 */		function create_keke_witkey_message_config(){		 		 $data =  array(); 					if(!is_null($this->_msg_cofig_id)){ 				 $data['msg_cofig_id']=$this->_msg_cofig_id;			}			if(!is_null($this->_reg_isnotice)){ 				 $data['reg_isnotice']=$this->_reg_isnotice;			}			if(!is_null($this->_task_pub_isnotice)){ 				 $data['task_pub_isnotice']=$this->_task_pub_isnotice;			}			if(!is_null($this->_tender_isnotice)){ 				 $data['tender_isnotice']=$this->_tender_isnotice;			}			if(!is_null($this->_task_auth_fail_isnotice)){ 				 $data['task_auth_fail_isnotice']=$this->_task_auth_fail_isnotice;			}			if(!is_null($this->_task_auth_success_isnotice)){ 				 $data['task_auth_success_isnotice']=$this->_task_auth_success_isnotice;			}			if(!is_null($this->_pay_fail_isnotice)){ 				 $data['pay_fail_isnotice']=$this->_pay_fail_isnotice;			}			if(!is_null($this->_user_auth_success_isnotice)){ 				 $data['user_auth_success_isnotice']=$this->_user_auth_success_isnotice;			}			if(!is_null($this->_user_auth_fail_isnotice)){ 				 $data['user_auth_fail_isnotice']=$this->_user_auth_fail_isnotice;			}			if(!is_null($this->_pay_success_isnotice)){ 				 $data['pay_success_isnotice']=$this->_pay_success_isnotice;			}			if(!is_null($this->_draw_success_isnotice)){ 				 $data['draw_success_isnotice']=$this->_draw_success_isnotice;			}			if(!is_null($this->_freeze_isnotice)){ 				 $data['freeze_isnotice']=$this->_freeze_isnotice;			}			if(!is_null($this->_task_freeze_isnotice)){ 				 $data['task_freeze_isnotice']=$this->_task_freeze_isnotice;			}			if(!is_null($this->_update_password_isnotice)){ 				 $data['update_password_isnotice']=$this->_update_password_isnotice;			}			if(!is_null($this->_msg_send_type)){ 				 $data['msg_send_type']=$this->_msg_send_type;			}			if(!is_null($this->_on_time)){ 				 $data['on_time']=$this->_on_time;			}			 return $this->_msg_cofig_id = $this->_db->inserttable($this->_tablename,$data,1,$this->_replace); 		 } 
	    /**		 * 编辑表keke_witkey_message_config的一个条记录		 * @return 返回影响的行数		 */		function edit_keke_witkey_message_config(){ 		 		 $data =  array();  					if(!is_null($this->_msg_cofig_id)){ 				 $data['msg_cofig_id']=$this->_msg_cofig_id;			}			if(!is_null($this->_reg_isnotice)){ 				 $data['reg_isnotice']=$this->_reg_isnotice;			}			if(!is_null($this->_task_pub_isnotice)){ 				 $data['task_pub_isnotice']=$this->_task_pub_isnotice;			}			if(!is_null($this->_tender_isnotice)){ 				 $data['tender_isnotice']=$this->_tender_isnotice;			}			if(!is_null($this->_task_auth_fail_isnotice)){ 				 $data['task_auth_fail_isnotice']=$this->_task_auth_fail_isnotice;			}			if(!is_null($this->_task_auth_success_isnotice)){ 				 $data['task_auth_success_isnotice']=$this->_task_auth_success_isnotice;			}			if(!is_null($this->_pay_fail_isnotice)){ 				 $data['pay_fail_isnotice']=$this->_pay_fail_isnotice;			}			if(!is_null($this->_user_auth_success_isnotice)){ 				 $data['user_auth_success_isnotice']=$this->_user_auth_success_isnotice;			}			if(!is_null($this->_user_auth_fail_isnotice)){ 				 $data['user_auth_fail_isnotice']=$this->_user_auth_fail_isnotice;			}			if(!is_null($this->_pay_success_isnotice)){ 				 $data['pay_success_isnotice']=$this->_pay_success_isnotice;			}			if(!is_null($this->_draw_success_isnotice)){ 				 $data['draw_success_isnotice']=$this->_draw_success_isnotice;			}			if(!is_null($this->_freeze_isnotice)){ 				 $data['freeze_isnotice']=$this->_freeze_isnotice;			}			if(!is_null($this->_task_freeze_isnotice)){ 				 $data['task_freeze_isnotice']=$this->_task_freeze_isnotice;			}			if(!is_null($this->_update_password_isnotice)){ 				 $data['update_password_isnotice']=$this->_update_password_isnotice;			}			if(!is_null($this->_msg_send_type)){ 				 $data['msg_send_type']=$this->_msg_send_type;			}			if(!is_null($this->_on_time)){ 				 $data['on_time']=$this->_on_time;			}			if($this->_where){ 				 return $this->_db->updatetable($this->_tablename,$data,$this->getWhere()); 			 } 			 else{ 				 $where = array('msg_cofig_id' => $this->_msg_cofig_id); 				 return $this->_db->updatetable($this->_tablename,$data,$where); 			} 		 } 
	    /**		 * 查询表keke_witkey_message_config,当有条件时返回有条件的ROW，否则返所有记录		 * @return 返回一个(array)关联数组		 */		function query_keke_witkey_message_config(){ 			 if($this->_where){ 				 $sql = "select * from $this->_tablename where ".$this->_where; 			 } 			 else{ 				 $sql = "select * from $this->_tablename"; 			 } 			 $this->_where = "";			 return $this->_dbop->query($sql); 		 } 
	    		function count_keke_witkey_message_config(){ 			 if($this->_where){ 				 $sql = "select count(*) as count from $this->_tablename where ".$this->_where; 			 } 			 else{ 				 $sql = "select count(*) as count from $this->_tablename"; 			 } 			 $this->_where = ""; 			 return $this->_dbop->getCount($sql); 		 } 
	    		function del_keke_witkey_message_config(){ 			 if($this->_where){ 				 $sql = "delete from $this->_tablename where ".$this->_where; 			 } 			 else{ 				 $sql = "delete from $this->_tablename where msg_cofig_id = $this->_msg_cofig_id "; 			 } 			 $this->_where = ""; 			 return $this->_dbop->execute($sql); 		 } 
	   
	    
	    
   }
 ?>