<?php
  class Keke_witkey_auth_item_class{
        var $_db;
        var $_tablename;
	    var $_dbop;
	    	 var $_auth_id; //主键		 var $_auth_title;		 var $_auth_day;		 var $_auth_small_ico;		 var $_auth_big_ico;		 var $_auth_desc;		 var $_auth_cash;		 var $_auth_period;		 var $_auth_open;		 var $_auth_show;		 var $_update_time;
	    var $_replace=0; //insert into or replace into ?
	    var $_where;     //查，改，删条件
	     function  keke_witkey_auth_item_class(){ //构造方法			 $this->_db = new db_factory ( );			 $this->_dbop = $this->_db->create(DBTYPE);			 $this->_tablename = TABLEPRE."witkey_auth_item";		 }
	    		function getAuth_id(){			 return $this->_auth_id ;		}		function getAuth_title(){			 return $this->_auth_title ;		}		function getAuth_day(){			 return $this->_auth_day ;		}		function getAuth_small_ico(){			 return $this->_auth_small_ico ;		}		function getAuth_big_ico(){			 return $this->_auth_big_ico ;		}		function getAuth_desc(){			 return $this->_auth_desc ;		}		function getAuth_cash(){			 return $this->_auth_cash ;		}		function getAuth_period(){			 return $this->_auth_period ;		}		function getAuth_open(){			 return $this->_auth_open ;		}		function getAuth_show(){			 return $this->_auth_show ;		}		function getUpdate_time(){			 return $this->_update_time ;		}		function getWhere(){			 return $this->_where ;		}
	    		function setAuth_id($value){			 $this->_auth_id = $value;		}		function setAuth_title($value){			 $this->_auth_title = $value;		}		function setAuth_day($value){			 $this->_auth_day = $value;		}		function setAuth_small_ico($value){			 $this->_auth_small_ico = $value;		}		function setAuth_big_ico($value){			 $this->_auth_big_ico = $value;		}		function setAuth_desc($value){			 $this->_auth_desc = $value;		}		function setAuth_cash($value){			 $this->_auth_cash = $value;		}		function setAuth_period($value){			 $this->_auth_period = $value;		}		function setAuth_open($value){			 $this->_auth_open = $value;		}		function setAuth_show($value){			 $this->_auth_show = $value;		}		function setUpdate_time($value){			 $this->_update_time = $value;		}		function setWhere($value){			 $this->_where = $value;		}
    	   public  function __set($property_name, $value) {
		 		$this->$property_name = $value;
			}
			public function __get($property_name) {
				if (isset ( $this->$property_name )) {
					return $this->$property_name;
				} else {
					return null;
				}
			}
	    /**		 * 表keke_witkey_auth_item创建或新增一条记录		 * @return 返回新增ID		 */		function create_keke_witkey_auth_item(){		 		 $data =  array();					if(!is_null($this->_auth_id)){				 $data['auth_id']=$this->_auth_id;			}			if(!is_null($this->_auth_title)){				 $data['auth_title']=$this->_auth_title;			}			if(!is_null($this->_auth_day)){				 $data['auth_day']=$this->_auth_day;			}			if(!is_null($this->_auth_small_ico)){				 $data['auth_small_ico']=$this->_auth_small_ico;			}			if(!is_null($this->_auth_big_ico)){				 $data['auth_big_ico']=$this->_auth_big_ico;			}			if(!is_null($this->_auth_desc)){				 $data['auth_desc']=$this->_auth_desc;			}			if(!is_null($this->_auth_cash)){				 $data['auth_cash']=$this->_auth_cash;			}			if(!is_null($this->_auth_period)){				 $data['auth_period']=$this->_auth_period;			}			if(!is_null($this->_auth_open)){				 $data['auth_open']=$this->_auth_open;			}			if(!is_null($this->_auth_show)){				 $data['auth_show']=$this->_auth_show;			}			if(!is_null($this->_update_time)){				 $data['update_time']=$this->_update_time;			}			 return $this->_auth_id = $this->_db->inserttable($this->_tablename,$data,1,$this->_replace);		 }
	    /**		 * 编辑表keke_witkey_auth_item的一个条记录		 * @return 返回影响的行数		 */		function edit_keke_witkey_auth_item(){		 		 $data =  array();					if(!is_null($this->_auth_id)){				 $data['auth_id']=$this->_auth_id;			}			if(!is_null($this->_auth_title)){				 $data['auth_title']=$this->_auth_title;			}			if(!is_null($this->_auth_day)){				 $data['auth_day']=$this->_auth_day;			}			if(!is_null($this->_auth_small_ico)){				 $data['auth_small_ico']=$this->_auth_small_ico;			}			if(!is_null($this->_auth_big_ico)){				 $data['auth_big_ico']=$this->_auth_big_ico;			}			if(!is_null($this->_auth_desc)){				 $data['auth_desc']=$this->_auth_desc;			}			if(!is_null($this->_auth_cash)){				 $data['auth_cash']=$this->_auth_cash;			}			if(!is_null($this->_auth_period)){				 $data['auth_period']=$this->_auth_period;			}			if(!is_null($this->_auth_open)){				 $data['auth_open']=$this->_auth_open;			}			if(!is_null($this->_auth_show)){				 $data['auth_show']=$this->_auth_show;			}			if(!is_null($this->_update_time)){				 $data['update_time']=$this->_update_time;			}			if($this->_where){				 return $this->_db->updatetable($this->_tablename,$data,$this->getWhere());			 }			 else{				 $where = array('auth_id' => $this->_auth_id);				 return $this->_db->updatetable($this->_tablename,$data,$where);			}		 }
	    /**		 * 查询表keke_witkey_auth_item,当有条件时返回有条件的ROW，否则返所有记录		 * @return 返回一个(array)关联数组		 */		function query_keke_witkey_auth_item(){			 if($this->_where){				 $sql = "select * from $this->_tablename where ".$this->_where;			 }			 else{				 $sql = "select * from $this->_tablename";			 }			 $this->_where = "";			 return $this->_dbop->query($sql);		 }		function count_keke_witkey_auth_item(){			 if($this->_where){				 $sql = "select count(*) as count from $this->_tablename where ".$this->_where;			 }			 else{				 $sql = "select count(*) as count from $this->_tablename";			 }			 $this->_where = "";			 return $this->_dbop->getCount($sql);		 }		function del_keke_witkey_auth_item(){			 if($this->_where){				 $sql = "delete from $this->_tablename where ".$this->_where;			 }			 else{				 $sql = "delete from $this->_tablename where auth_id = $this->_auth_id ";			 }			 $this->_where = "";			 return $this->_dbop->execute($sql);		 }
   }
 ?>